import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'
import Instagram from '../components/Instagram'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Ashwin Joshi' message='Web Developer! Built Responsive site with mern stack'/>
      <Slider slides={SliderData}/>
      <Instagram/>

    </div>
  )
}
